### ISSUE TITLE
Winrm hangs when remote client doesn't exist

### ISSUE THREAD

**Issue by L1ghtman2k** [masterzen/winrm#108]
Hey, 

I utilize the project in an environment where I need to run winrm constantly on arbitrary hosts at very specific times. The current implementation allows inserting timeouts, however, it seems like if the remote host does not exist, the code will hang for longer than timeout provided because of the following: https://github.com/masterzen/winrm/blob/c42b5136ff886aff9dba40fb3670281f0d583db8/http.go#L97
It seems like the most straight forward solution would be to allow passing timeouts into httpClient:
https://github.com/masterzen/winrm/blob/c42b5136ff886aff9dba40fb3670281f0d583db8/http.go#L89

Any thoughts?

Thanks for the awesome project!

**Comment by masterzen** [comment]
Thanks for your report!

There are several thing at play here, I think. 
First, when you say the host doesn't exist, I assume the DNS exists, but the IP address is not assigned and nobody answers, right?

The default transport contains a hardcoded Dial Timeout of 30 seconds:
https://github.com/masterzen/winrm/blob/c42b5136ff886aff9dba40fb3670281f0d583db8/http.go#L49-L52

So if the client is not able to connect to the HTTP endpoint in those 30 seconds, it should normally error. 

So I tested it:

```
% time winrm -hostname X.Y.Z.92 -username <redacted> -password <redacted> 'ipconfig /all'
unknown error Post http://X.Y.Z.92:5985/wsman: dial tcp X.Y.Z.92:5985: i/o timeout
winrm -hostname X.Y.Z.92 -username <redacted> -password <redacted>   0.01s user 0.01s system 0% cpu 30.030 total
```

Indeed it failed after 30s, which is the hardcoded timeout in such case.

If you want to control the connection timeout (because 30s might be too long for your use case), you can do so by calling `NewClientWithParameters` like this (warning pseudocode not tested):

```go
    endpoint := winrm.NewEndpoint("host", 5985, false, false, nil, nil, nil, 0)

    params := winrm.DefaultParameters
    params.Dial = (&net.Dialer{
		Timeout:   5 * time.Second,
		KeepAlive: 30 * time.Second,
	}).Dial
 
    client, err := winrm.NewClientWithParameters(endpoint, "test", "test", params)
    if err != nil {
        panic(err)
    }
 
    _, err = client.RunWithInput("ipconfig", os.Stdout, os.Stderr, os.Stdin)
    if err != nil {
        panic(err)
    }
```

Indeed we could make that easier...
Let me know if that doesn't solve your issue,

Thanks!

**Comment by L1ghtman2k** [comment]
```
First, when you say the host doesn't exist, I assume the DNS exists, but the IP address is not assigned and nobody answers, right?
```
Correct, I tried directly on IP that doesn't exist, but I think the same logic applies here.

My current workaround is to check weather the port on a remote machine is open prior to attempting winrm connection:
```
	conn, err := net.DialTimeout("tcp", net.JoinHostPort(Address, Port), time.Until(e.Deadline())/3)
	if err != nil {
		return false, "Port was not open on a remote host", err
	}
```

Thanks for the solution provided, it is good enough for me!
