### ISSUE TITLE
'Attempting WinRM connection' - timeout for httpClient

### ISSUE THREAD

**Issue by mwieczorek** [masterzen/winrm#46]
I have problem with building VM with Packer, but I think the issue can be in winrm (that's why I create issue here, not in Packer repo)

My host: Windows 8.1
Packer version: 0.10.1

I want to build: https://github.com/StefanScherer/packer-windows/blob/my/windows_2016_docker.json (-only=virtualbox-iso)
Log in gist: https://gist.github.com/mwieczorek/83e6034fc41f06a8583bc3315646ab1b

Packer is "Attempting WinRM connection..." every 5 seconds. But after a few minutes it stops 'attempting'.
Provisioning of the machine continue, and after a while winrm is available (I'm able to Enter-PSSession from my host laptop to VM).

I checked network traffic between my laptop and VM (using Microsoft Message Analyzer - https://www.microsoft.com/en-us/download/details.aspx?id=44226). 
I see that last attempt was waiting for response about 76 seconds. So I started to wonder if it's related to some kind of timeout. (I attached session from that tool - [packer.zip](https://github.com/masterzen/winrm/files/260281/packer.zip) )

I cloned Packer from Github and looked at [http.go](https://github.com/mitchellh/packer/blob/master/vendor/github.com/masterzen/winrm/winrm/http.go) file.
I see there:
```
func Http_post(client *Client, request *soap.SoapMessage) (response string, err error) {
	httpClient := &http.Client{Transport: client.transport}
```

I don't know Go but I thought: "no timeout is set for httpClient, so I'll try to set it":

```
func Http_post(client *Client, request *soap.SoapMessage) (response string, err error) {
	httpClient := &http.Client{Transport: client.transport, Timeout:100*time.Second}
```
	

And it looks like it fixed the problem. See log in gist: https://gist.github.com/mwieczorek/b29a253cc38cdf1ed43e32b356b74816

So my question is: is the timeout not set on purpose?
Or maybe it should/can be set?

**Comment by masterzen** [comment]
@mwieczorek,

I'm not sure I understand what you mean.
Is that your VM has no winrm and then since there is no timeout packer can't make any progress if the vm doesn't answer to winrm connections?

If yes, then that's true we would need a connection timeout of some sort. I would have thought that if winrm wasn't active on the guest, then the connection wouldn't proceed and we would return immediately with an error (without waiting).

The only reason I think we could end up waiting, is if there is a firewall running on the guest dropping winrm connections until it is properly configured.

Anyway, I think adding a timeout is harmless. I'll see what I can do.

Thanks for the report.

**Comment by mwieczorek** [comment]
> The only reason I think we could end up waiting, is if there is a firewall running on the guest dropping winrm connections until it is properly configured.

I think it can be true. Packer is waiting when the winrm is not configured yet, but maybe some default firewall rules are. 

> if winrm wasn't active on the guest, then the connection wouldn't proceed and we would return immediately with an error (without waiting).

Yes, in logs (from gist) we have:
`2016/05/11 22:49:25 packer.exe: 2016/05/11 22:49:25 [ERROR] WinRM connection err: unknown error Post http://127.0.0.1:2841/wsman: EOF`
And then suddenly it's waiting...
So it can be firewall.

Anyway:
If you can add timeout I will be grateful.

**Comment by masterzen** [comment]
@mwieczorek , I've done several tests with firewall off/on. Indeed with firewall on, I get the same error message as you.

I have a fix almost ready (yours unfortunately is not correct since the timeout you set is an end-to-end timeout and not only a connect and wait for response timeout). Some WinRM requests can take a long time before something happens (like for instance fetching command `stdout`).
