### ISSUE TITLE
"http error: 500" on latest master

### ISSUE THREAD

**Issue by hach-que** [masterzen/winrm#48]
As part of our deployment process, we build and deploy the latest winrm version.  We've noticed that master now seems to error with "http error: 500" when we're doing long running commands (usually after about 70 seconds or so).

This previously didn't happen, and it doesn't happen on versions of WinRM that only have these options (not sure which commit this was built from):

```
Usage of winrm:
  -hostname="localhost": winrm host
  -password="vagrant": winrm admin password
  -port=5985: winrm port
  -username="vagrant": winrm admin username
```

I'm sure we've been running newer versions than this, but this was the version of WinRM I could find since I needed to restore service quickly.

**Comment by hoenirvili** [comment]
#47 I think i'ts because of this issue @masterzen

**Comment by masterzen** [comment]
Yes @hoenirvili, it is probably the problem.
@hach-que can you edit the default timeout of 60s here: https://github.com/masterzen/winrm/blob/master/winrm/endpoint.go#L38
and put a larger number matching what your commands do.
Then let me know if that succeeds or fails, I'll then raise the default timeout.

**Comment by masterzen** [comment]
@hach-que BTW, do you use the `winrm` executable or directly the API?
Normally, when using the `winrm` executable, there shouldn't be any timeout by default unless you use the `-timeout` option.
Can you confirm how you use this project?

**Comment by hach-que** [comment]
Via the executable

**Comment by hoenirvili** [comment]
@masterzenI think it's a good time to make this proposal
I propose to decouple the executable code from the api code. It's starts to be ugly and we should user a library-framework to easily customize , and develop our binary-executable-tool.
This way it's more easily to make changes to the API without adding/deleting things on executable and vice-versa. Plus a better error handling system in the code overal. What do you think?

We could easily use this wonderful libraries for command line apps.
https://github.com/spf13/cobra
https://github.com/codegangsta/cli
https://github.com/hoenirvili/Skapt
https://github.com/alecthomas/kingpin

**Comment by masterzen** [comment]
@hach-que would it be possible for you to `git-bisect` and find the commit that starts the issue?
The `winrm` executable as of current master has no timeout by default (just tested again), so the problem might be a prior commit which we need to find.

**Comment by masterzen** [comment]
@hoenirvili , please open a new issue for separating the cli executable from the library.

**Comment by hach-que** [comment]
Unfortunately this is a production system that the issue occurs on, so I can't be `git bisect` testing which version works (and because it's in a cluster, there's no way to reliably force a build to occur on the machine that I'm A/B testing on without interrupting other services).

We use `winrm` like we would use `ssh` - the concept of having timeouts here doesn't make a lot of sense, in the same way you wouldn't expected `ssh user@host command` to have a built-in timeout of 60 seconds.

**Comment by masterzen** [comment]
@hach-que, I'll try to reproduce the issue and do the git bisect.

What kind of commands were you running that were giving the `http 500` error you were mentioning?
What version of go did you use to compile the project?
HTTP 500 error codes usually refers to a server-side error, not a client side. Would you be able to log in the affected systems and find the winrm event logs and see if something meaningful has been logged at the time of the errors to help troubleshooting?

I don't think this last timeout patch is the culprit as normally when using the `winrm` command there is no timeout involved unless using the `-timeout` command-line argument.

From what you tell, I suppose you've "lost" the last version of winrm you were using, right?
Since you contributed a patch earlier, I would suppose that your patch is the latest version working for you.

Now for the reason there is a timeout: winrm is a stateful protocol implemented on a stateless protocol. So running a command is in fact a succession of small HTTP requests/responses with the server. There are plenty of use cases (like using Packer, which was the primary goal of this tool), where you want to know early that there is no server, hence we needed a "connection" timeout (like there's one in `ssh` by the way). Still, there is an internal server-side timeout (which you can find in the `Parameters` structure in the library) that if I'm not mistaken will trigger if your commands don't terminate before its value (which is 60s by default).

**Comment by masterzen** [comment]
@hach-que ok, I think I've found the problem. We somehow lost your code from this commit e776fa0185887e19d080602deb93484e2533e396 which means we propagate now the OperationTimeout up to the layer stack aborting the command run instead of gracefully ignoring it and retrying.

This is also related to @pecigonzalo PR #26, which I'm going to merge soon.

This isn't related to my latest code from PR #47 .

**Comment by masterzen** [comment]
@hach-que would you be able to test the code in PR #50?
