### ISSUE TITLE
Vendoring this library causes build failures

### ISSUE THREAD

**Issue by Xiol** [masterzen/winrm#76]
Hi,

We have a project using this library which won't build if we vendor this library (using [dep](https://github.com/golang/dep)).

```
vendor/github.com/masterzen/winrm/auth.go:28:18: cannot use "[snip]/vendor/github.com/masterzen/azure-sdk-for-go/core/tls".Config literal (type *"[snip]/vendor/github.com/masterzen/azure-sdk-for-go/core/tls".Config) as type *"[snip]/vendor/github.com/MSOpenTech/azure-sdk-for-go/core/tls".Config in field value
```

Without vendoring, the everything builds fine. 

I can see that you're using your own fork of `azure-sdk-for-go`, but dep seems to be pulling in the MSOpenTech one as well for some reason - I'm not entirely sure why it's doing this as all we're directly importing into our project is this winrm library. 

Output from `dep status`, relevant packages only:

```
PROJECT                                             CONSTRAINT     VERSION        REVISION  LATEST       PKGS USED
github.com/Azure/go-ntlmssp                         branch master  branch master  c92175d   c92175d      1   
github.com/MSOpenTech/azure-sdk-for-go              ^1.2.0         v1.2           0fbd371   v1.2         2   
github.com/masterzen/azure-sdk-for-go               ^1.2.0         v1.2           0fbd371   v1.2         2   
github.com/masterzen/simplexml                      branch master  branch master  4572e39   4572e39      1   
github.com/masterzen/winrm                          branch master  branch master  a2df6b1   a2df6b1      2   
github.com/nu7hatch/gouuid                          branch master  branch master  179d4d0   179d4d0      1   
```

Some of the files in your `azure-sdk-for-go` fork appear to be referencing the MSOpenTech files for imports, so I think it might be this causing the problem.

**Comment by masterzen** [comment]
Hi,

This is very strange since there's no references at all to `MSOpenTech` in this project nor in the `azure-sdk-for-go` fork I'm using.

I'm a bit out of clue about this issue. Try to clean your go pkg, maybe you got an older version of winrm that pointed to the MSOpenTech version ?

On a side note, this fork is not needed since in Go 1.7 (or was it 1.8), they integrated the necessary bits that were implemented in the `azure-sdk-for-go` (PR much welcome of course :)

**Comment by masterzen** [comment]
Oops, I misread your last sentence. Indeed that's probably the cause.

So that leaves us with two options:
* remove completely the dependency and assume Go >= 1.7
* clean the fork to remove mention of MSOpenTech

I'm all in favor of option 2. I don't really have the time to address this in the coming weeks, but I'm welcome to any PR.

**Comment by Xiol** [comment]
Figure this out - by default dep was pulling in the v1.2 tag as that was the latest available tag. The master branch doesn't contain the references back to the MSOpenTech library though, so I changed the constraint in dep to pull in master rather than v1.2 which resolves the issue (with some extra faffing).

Will have to pin it to the current master commit to ensure it doesn't break on changes, but I think I'm good. Thanks.

**Comment by masterzen** [comment]
OK, thanks for the explanation!

**Comment by rmb938** [comment]
I am having a similar issue, winrm is a dependency of another library I am pulling in. Is there any reason you are using your own fork of the azure sdk instead of the official one?

**Comment by rmb938** [comment]
Ah ok, makes sense. I have no problem making a PR to migrate things in the next week or so. Would you be willing to help test it? I haven't done any windows administration so I wouldn't really know how to properly test things.

**Comment by masterzen** [comment]
@rmb938 I don't have a lot of bandwidth recently, and will have very low Internet connectivity until end of July. Feel free to send the PR, I'll do my best to test/review it. Otherwise, I'll probably do the fix during the summer.
